name: JE_Editor Dev Python3.9

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]
  schedule:
    - cron: "0 4 * * *"

permissions:
  contents: read

jobs:
  build_dev_version:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip wheel
          pip install -r dev_requirements.txt
      - name: Test Start Editor
        run: python ./test/qt_ui/unit_test/start_qt_ui.py
      - name: Test Extend Editor
        run: python ./test/qt_ui/unit_test/extend_test.py